### ISSUE TITLE
Not working in Python 3.10

### ISSUE THREAD

**Issue by Nekoraru22** [NexInfinite/videotoascii#2]
I had to change the regex import to re to avoid problems but now `PyInquirer` don't let me execute the ascii.py. I read tha's because the last version of python 3.10.

The error:
```
Traceback (most recent call last):
  File "/home/neko/Escritorio/videotoascii/ascii.py", line 8, in <module>
    from PyInquirer import prompt, Validator, ValidationError
ModuleNotFoundError: No module named 'PyInquirer'

```
![image](https://user-images.githubusercontent.com/57575090/153937276-67cbf4ed-8348-41c5-b6ff-000853107bb1.png)

**Comment by NexInfinite** [comment]
Hey!
Thanks for reaching out, please try install PyInquirer by the command:

`pip3 install PyInquirer`

Let me know if that helps out.

**Comment by Nekoraru22** [comment]
I alredy tried, but is the same

**Comment by NexInfinite** [comment]
Sorry to hear that, could you please send the output of the command
`python --version` and `python3 --version`

Also can you please try to do the command
`python3 video_render.py <url>`, this should bypass the cli and just run the video render script.

**Comment by NexInfinite** [comment]
Also another thought, try run the script without sudo. If you run it in sudo it may be running python as sudo and so you'll need to install pip packages via `sudo pip3 install <package>`.

**Comment by NexInfinite** [comment]
One more note, if you are still having issues and want to run this in python 3.8 you can set up a venv. When creating this project I used a venv of python3.8 and this is what it has been tested in. To do this follow the instructions below.

# Instructions
## Create the venv
`cd your/project/path`
`sudo apt install python3.8` or `sudo pacman -S python3.8` or any other way of installing python3.8 on your system
`python3.8 -m venv venv`

## Load into venv
`source venv/bin/activate`

## Run scripts
`python main.py`

**Comment by Nekoraru22** [comment]
# Python version:
![image](https://user-images.githubusercontent.com/57575090/153971664-4bdeb7f9-4410-4972-9116-be499c15b7ec.png)

---

## The first command works for me:
![image](https://user-images.githubusercontent.com/57575090/153971731-9cc2ee3a-7dfd-4b12-963c-497c88a8dab4.png)
![image](https://user-images.githubusercontent.com/57575090/153971929-1735c7ff-c141-4f86-bc1f-c9baab0073d1.png)
### But I would have liked to see it as seen in the gif:
![image](https://user-images.githubusercontent.com/57575090/153972659-ae29d951-806b-46cc-871a-f81e769c31d6.png)

---

## I have been doing it with 'sudo' because without it I had more errors:
![image](https://user-images.githubusercontent.com/57575090/153972375-05508501-1cc9-4084-a7da-4bd595ade403.png)

---

## I tried to install all the necessary packages and edit the code a little bit but to no avail. It is enough for me with the above command, thank you very much!

**Comment by NexInfinite** [comment]
Ah I see, well if you want the cli you should try use the venv but if you want it to be like the gif shown above set the flag`--video_mode=true`. This will make it look like above. Let me know if that helps.

(Also sweet setup)

**Comment by Nekoraru22** [comment]
Just what i was looking for!
I appreciate <3

Have a good day 😺
